### ISSUE TITLE
Is is possible to fix app hostname somehow?

### ISSUE THREAD

**Issue by ypadlyak** [michaelshobbs/dokku-logspout#16]
The hostname is dynamically generated, I believe, by docker. It is impossible to distinguish logs from certain Dokku application in Papertrail.

**Comment by michaelshobbs** [comment]
I use https://github.com/michaelshobbs/dokku-hostname to set a consistent hostname.

**Comment by ashleyconnor** [comment]
Not managed to get this working. I'm probably missing something.

![https://www.dropbox.com/s/an3p7mxfkduqd8s/Screenshot%202016-10-11%2023.43.10.png?dl=1](https://www.dropbox.com/s/an3p7mxfkduqd8s/Screenshot%202016-10-11%2023.43.10.png?dl=1)

My hostname is fixed in my logs as `rublix` although the hostname of the system is `rublix.com`. So right now I can't distinguish between containers.

`.logspout/OPTS`:

```
export DOKKU_LOGSPOUT_PORT=18000
export DOKKU_LOGSPOUT_IMAGE_VERSION=v3.1
export DOKKU_LOGSPOUT_SYSLOG_SERVER=syslog+tls://logs.papertrailapp.com:5XX
```

`.logspout/ENV`

```
SYSLOG_HOSTNAME=rublix.com
SYSLOG_TAG={{.Container.Config.Hostname}}
```

**Comment by michaelshobbs** [comment]
IIRC, in that output `dokku` is the hostname reported by the container and `rublix` is the container name. In recent versions of `dokku`, it names the final running app container in the format `appname`.`processname`.`processindex`. 

If you are using the `dokku-hostname` plugin, it will always pass the `--hostname` docker arg as [such](https://github.com/michaelshobbs/dokku-hostname/blob/a196693b52f6bc5f9335e026ebe7909b01e20c61/docker-args#L16) but doesn't know anything about the container name. 

If you still can't get it working, please open a new issue or join me on the dokku [slack room](https://glider-slackin.herokuapp.com/) or [irc channel](https://webchat.freenode.net/?channels=dokku)
