### ISSUE TITLE
Route nginx access logs

### ISSUE THREAD

**Issue by dulacp** [michaelshobbs/dokku-logspout#20]
This plugin is awesome, except for not routing nginx logs.
Is it something you had in mind? or already ruled out? I prefer to ask before hacking a PR.

Cheers

**Comment by michaelshobbs** [comment]
To clarify, this plugin solely ensures that the logspout container is running. Additionally, logspout only sends docker container logs to a syslog endpoint. I consider shipping logs on the host file system outside the scope of this plugin primarily because solutions for this already exist. 

To your specific concern, I would probably use an  rsyslog config to handle this. Sounds like a good idea for a new dokku community plugin actually. Think something like a light weight wrapper cli around creating the aforementioned rsyslog config file and reloading the rsyslog config.

**Comment by dulacp** [comment]
It's cristal clear.
I will start a project then, as you suggested just a thin wrapper cli around rsyslog sounds like a nice plan.
Thanks
