### ISSUE TITLE
Recommended log viewer (self hosted)?

### ISSUE THREAD

**Issue by wootwoot1234** [michaelshobbs/dokku-logspout#29]
I'm currently using loggly.com to view my log outputs but I'm hitting my limit almost every day (for the free plan).  Do you know of a good self hosted alternative?  Any you would recommend?  Or maybe a hosted alternative to loggly that will allow for more log uploads and alerts?

I'm using this for a hobby project of mine that I don't want to spend money on.

Thanks!

**Comment by michaelshobbs** [comment]
I'm not sure any self-hosted stack would be any cheaper. ELK (elasticsearch/logstash/kibana) takes a nominal bit of processing/storage. You could maybe run a small syslog instance on DO or something and just trim the stored logs via a cron job. However, in the end if the logs are important enough to view, you'll probably count out ahead by using something hosted. I've not compared the landscape in awhile but papertrail's model is pretty good since they give you multiple levers to control your cost.

**Comment by andyklimczak** [comment]
not sure about loggly, but on papertrail you can filter out messages using regex. that might help you if you have a chatty process that isn't that useful

**Comment by ypadlyak** [comment]
@andyklimczak Papertrail has incoming filleting too
